---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/admins":
    get:
      summary: list admins
      responses:
        '200':
          description: successful
    post:
      summary: create admin
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
  "/admins/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show admin
      responses:
        '200':
          description: successful
    patch:
      summary: update admin
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
              - name
              - email
              - password
    delete:
      summary: delete admin
      responses:
        '200':
          description: successful
  "/organisations/{organisation_id}/beneficiaries":
    parameters:
    - name: organisation_id
      in: path
      description: organisation_id
      required: true
      schema:
        type: string
    get:
      summary: list beneficiaries
      responses:
        '200':
          description: successful
  "/beneficiaries":
    get:
      summary: list beneficiaries
      responses:
        '200':
          description: successful
    post:
      summary: create beneficiary
      responses:
        '200':
          description: successful
  "/beneficiaries/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show beneficiary
      responses:
        '200':
          description: successful
    patch:
      summary: update beneficiary
      responses:
        '200':
          description: successful
    delete:
      summary: delete beneficiary
      responses:
        '200':
          description: successful
  "/donations":
    get:
      summary: list donations
      responses:
        '200':
          description: successful
    post:
      summary: create donation
      responses:
        '200':
          description: successful
  "/donations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show donation
      responses:
        '200':
          description: successful
    patch:
      summary: update donation
      responses:
        '200':
          description: successful
  "/organisations/{organisation_id}/donations":
    parameters:
    - name: organisation_id
      in: path
      description: organisation_id
      required: true
      schema:
        type: string
    get:
      summary: list donations
      responses:
        '200':
          description: successful
  "/donors":
    get:
      summary: list donors
      responses:
        '200':
          description: successful
    post:
      summary: create donor
      responses:
        '200':
          description: successful
  "/donors/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show donor
      responses:
        '200':
          description: successful
    patch:
      summary: update donor
      responses:
        '200':
          description: successful
    delete:
      summary: delete donor
      responses:
        '200':
          description: successful
  "/organisations/{organisation_id}/inventories":
    parameters:
    - name: organisation_id
      in: path
      description: organisation_id
      required: true
      schema:
        type: string
    get:
      summary: list inventories
      responses:
        '200':
          description: successful
  "/inventories":
    get:
      summary: list inventories
      responses:
        '200':
          description: successful
    post:
      summary: create inventory
      responses:
        '200':
          description: successful
  "/inventories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show inventory
      responses:
        '200':
          description: successful
    patch:
      summary: update inventory
      responses:
        '200':
          description: successful
    delete:
      summary: delete inventory
      responses:
        '200':
          description: successful
  "/organisations":
    get:
      summary: list organisations
      responses:
        '200':
          description: successful
    post:
      summary: create organisation
      responses:
        '200':
          description: successful
  "/organisations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show organisation
      responses:
        '200':
          description: successful
    patch:
      summary: update organisation
      responses:
        '200':
          description: successful
    delete:
      summary: delete organisation
      responses:
        '200':
          description: successful
  "/reminders":
    get:
      summary: list reminders
      responses:
        '200':
          description: successful
    post:
      summary: create reminder
      responses:
        '200':
          description: successful
  "/reminders/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reminder
      responses:
        '200':
          description: successful
    patch:
      summary: update reminder
      responses:
        '200':
          description: successful
    delete:
      summary: delete reminder
      responses:
        '200':
          description: successful
  "/stories":
    get:
      summary: list stories
      responses:
        '200':
          description: successful
    post:
      summary: create story
      responses:
        '200':
          description: successful
  "/stories/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show story
      responses:
        '200':
          description: successful
    patch:
      summary: update story
      responses:
        '200':
          description: successful
    delete:
      summary: delete story
      responses:
        '200':
          description: successful
  "/transactions":
    get:
      summary: list transactions
      responses:
        '200':
          description: successful
    post:
      summary: create transaction
      responses:
        '200':
          description: successful
  "/transactions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show transaction
      responses:
        '200':
          description: successful
    patch:
      summary: update transaction
      responses:
        '200':
          description: successful
    delete:
      summary: delete transaction
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: http://127.0.0.1:3000/
