require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/donation_activities", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # DonationActivity. As you add validations to DonationActivity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DonationActivity.create! valid_attributes
      get donation_activities_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      donation_activity = DonationActivity.create! valid_attributes
      get donation_activity_url(donation_activity)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_donation_activity_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      donation_activity = DonationActivity.create! valid_attributes
      get edit_donation_activity_url(donation_activity)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DonationActivity" do
        expect {
          post donation_activities_url, params: { donation_activity: valid_attributes }
        }.to change(DonationActivity, :count).by(1)
      end

      it "redirects to the created donation_activity" do
        post donation_activities_url, params: { donation_activity: valid_attributes }
        expect(response).to redirect_to(donation_activity_url(DonationActivity.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DonationActivity" do
        expect {
          post donation_activities_url, params: { donation_activity: invalid_attributes }
        }.to change(DonationActivity, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post donation_activities_url, params: { donation_activity: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested donation_activity" do
        donation_activity = DonationActivity.create! valid_attributes
        patch donation_activity_url(donation_activity), params: { donation_activity: new_attributes }
        donation_activity.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the donation_activity" do
        donation_activity = DonationActivity.create! valid_attributes
        patch donation_activity_url(donation_activity), params: { donation_activity: new_attributes }
        donation_activity.reload
        expect(response).to redirect_to(donation_activity_url(donation_activity))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        donation_activity = DonationActivity.create! valid_attributes
        patch donation_activity_url(donation_activity), params: { donation_activity: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested donation_activity" do
      donation_activity = DonationActivity.create! valid_attributes
      expect {
        delete donation_activity_url(donation_activity)
      }.to change(DonationActivity, :count).by(-1)
    end

    it "redirects to the donation_activities list" do
      donation_activity = DonationActivity.create! valid_attributes
      delete donation_activity_url(donation_activity)
      expect(response).to redirect_to(donation_activities_url)
    end
  end
end
